CREATE TABLE [dbo].[PRZEDMIOT] (
    [ID]                    INT            IDENTITY (1, 1) NOT NULL,
    [NAZWA]                 NVARCHAR (250) NOT NULL,
    [NAZWISKO_PROWADZACEGO] NVARCHAR (50)  NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

