CREATE TABLE [dbo].[PRZYPISANIE] (
    [ID]           INT IDENTITY (1, 1) NOT NULL,
    [STUDENT_ID]   INT NULL,
    [PRZEDMIOT_ID] INT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PRZYPISANIE_PRZEDMIOT] FOREIGN KEY ([PRZEDMIOT_ID]) REFERENCES [dbo].[PRZEDMIOT] ([ID]),
    CONSTRAINT [FK_PRZYPISANIE_STUDENT] FOREIGN KEY ([ID]) REFERENCES [dbo].[STUDENT] ([ID])
);

