CREATE TABLE [dbo].[STUDENT] (
    [ID]     INT            IDENTITY (1, 1) NOT NULL,
    [IMIE]   NVARCHAR (250) NOT NULL,
    [INDEKS] INT            NOT NULL,
    [PESEL]  NVARCHAR (50)  NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    UNIQUE NONCLUSTERED ([INDEKS] ASC)
);

