CREATE DATABASE kol_database
GO
use kol_database

CREATE TABLE DBO.STUDENT (
[ID] INT PRIMARY KEY IDENTITY ,
[IMIE] NVARCHAR (250)NOT NULL,
[INDEKS] INT UNIQUE NOT NULL,
[PESEL] NVARCHAR (50) NOT NULL ,
[NIP] INT ,
[PLEC] NVARCHAR (25)
)
CREATE TABLE DBO.PRZEDMIOT (
[ID] INT PRIMARY KEY IDENTITY ,
[NAZWA] NVARCHAR (250)NOT NULL,
[NAZWISKO_PROWADZACEGO] NVARCHAR (50) NOT NULL
)
CREATE TABLE DBO.PRZYPISANIE (
[ID] INT PRIMARY KEY IDENTITY,
[STUDENT_ID] INT ,
[PRZEDMIOT_ID] INT,
[DATA_PRZYPISANIA] DATE
)